[project]
name = "testing-starter-backend"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn>=0.30.0",
    "httpx>=0.27.0",
    "pydantic>=2.6.0",
]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]